---
title: "EOPE EWAS Visualization"
author: "William Casazza"
date: "April 8, 2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::read_chunk("run_ewas.R")
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages,echo=FALSE}
```

## Dataset from wilson et al 2016
Download from [GEO](https://ftp.ncbi.nlm.nih.gov/geo/series/GSE100nnn/GSE100197/matrix/GSE100197_series_matrix.txt.gz)
```{r load_data}
```
## Fit linear model and relevant contrasts
```{r run_fit}
colnames(contrasts)
```
## Extract stats from relevant comparisons
```{r}
eope_stats <- topTable(fitCont,coef = "preTEOPE", adjust.method = "BH", p.value = 0.05, lfc = 0.1, number = Inf)
nrow(eope_stats)
eope_sex <- topTable(fitCont,coef = "sex", adjust.method = "BH", p.value = 0.05, lfc = 0.1, number = Inf)
nrow(eope_sex)
```

Published data
```{r}
pub_dme <- read.csv(
  "ddx391_ST1_PersistentHits599_GeneInfo_2017.csv", 
  stringsAsFactors = F)
pub_dme <- pub_dme[pub_dme$Probe %in% rownames(eope_stats),]
```

## Plots
### Correlation
```{r}
shared_hits_df <- as.data.frame(cbind(pub_dme,eope_stats[pub_dme$Probe,]))
corr <- cor.test(-log10(shared_hits_df$adj.P.Val),-log10(shared_hits_df$EOPE.vs.Pre.term.p.value..Discovery.Cohort),method="pearson")
corr2 <-cor.test(shared_hits_df$EOPE.Δβ..Discovery.Cohort,shared_hits_df$logFC, method = "pearson")
ggplot(shared_hits_df, aes(-log10(EOPE.vs.Pre.term.p.value..Discovery.Cohort),-log10(adj.P.Val))) + 
  geom_point()+  
  coord_cartesian(xlim=c(0,15),ylim=c(0,15))+
  geom_abline(slope = 1,intercept = c(0,0))+
  ggtitle(sprintf("R:%0.3f",corr$estimate))
ggplot(shared_hits_df, aes(EOPE.Δβ..Discovery.Cohort,logFC)) + 
  geom_point()+  
  geom_abline(slope = 1,intercept = c(0,0))+
  ggtitle(sprintf("R:%0.3f",corr2$estimate))
```

```{r}
plot_stats <- function(cont){
all_eope_stats <- topTable(fitCont,coef = cont, adjust.method = "BH",number = Inf)
all_eope_stats$color <- ifelse(
  all_eope_stats$adj.P.Val <0.05,
  ifelse(
    all_eope_stats$logFC > 0.1,
    "DME_pos",
    ifelse(all_eope_stats$logFC < -0.1,
      "DME_neg",
      "not DME"
    )),
  "not DME")
p <- ggplot(all_eope_stats, aes(logFC,-log10(adj.P.Val),color=color)) + 
  geom_point(size=1,alpha=0.3)+
  scale_color_manual(values = c("DME_pos"="dark green","DME_neg"="red","not DME"="black"))+
  coord_cartesian(xlim=c(-0.3,0.3),ylim=c(0,10))
print(p)
return(all_eope_stats)
}
eope_all_stat <-plot_stats("preTEOPE")
lope_all_stat<- plot_stats("termLOPE")
```
```{r}
sum(abs(eope_all_stat$logFC) >0.1& eope_all_stat$adj.P.Val <0.05)
sum(abs(lope_all_stat$logFC) > 0.1 & lope_all_stat$adj.P.Val <0.05)
```

